import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Navbar } from '../../components/NavBar';
import styles from '../../styles/Home.module.css';

const ContactPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>NextJS Basics - Home</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='keywords' content='NextJS, Basics' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />

			<main className={styles.main}>
				<h1>ContactPage</h1>
				<h1 className={styles.title}>
					Go To <Link href='/'>HomePage</Link>
				</h1>

				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/index.jsx</code>
				</p>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default ContactPage;
